import { MigrationInterface, QueryRunner } from "typeorm";

export class dbinit1668203949098 implements MigrationInterface {
    name = 'dbinit1668203949098'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_item" ("generatedID" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "itemCategoryID" integer NOT NULL, "itemSubcategoryID" integer NOT NULL, "itemSecondarySubCategoryID" integer NOT NULL, "itemID" integer NOT NULL, "name" varchar NOT NULL, "shortDescription" varchar NOT NULL, "longDescription" varchar NOT NULL, "price" integer NOT NULL, "inStock" boolean NOT NULL, "itemTypeTypeID" integer, "itemCategoryCatID" integer, "itemSubCategorySubCatID" integer, "itemSecondarySubCategorySubCatID" integer, CONSTRAINT "FK_afffb0a7530540913cc8651f81f" FOREIGN KEY ("itemSecondarySubCategorySubCatID") REFERENCES "item_sub_category" ("subCatID") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0400fef2a2f4557489b13940fdc" FOREIGN KEY ("itemSubCategorySubCatID") REFERENCES "item_sub_category" ("subCatID") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_b352f619a37b102f8fb8a58fcf7" FOREIGN KEY ("itemCategoryCatID") REFERENCES "item_category" ("catID") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4eae565e0e6ff2ea65ae3aa7ef4" FOREIGN KEY ("itemTypeTypeID") REFERENCES "item_type" ("typeID") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_item"("generatedID", "itemCategoryID", "itemSubcategoryID", "itemSecondarySubCategoryID", "itemID", "name", "shortDescription", "longDescription", "price", "inStock", "itemTypeTypeID", "itemCategoryCatID", "itemSubCategorySubCatID", "itemSecondarySubCategorySubCatID") SELECT "generatedID", "itemCategoryID", "itemSubcategoryID", "itemSecondarySubCategoryID", "itemID", "name", "shortDescription", "longDescription", "price", "inStock", "itemTypeTypeID", "itemCategoryCatID", "itemSubCategorySubCatID", "itemSecondarySubCategorySubCatID" FROM "item"`);
        await queryRunner.query(`DROP TABLE "item"`);
        await queryRunner.query(`ALTER TABLE "temporary_item" RENAME TO "item"`);
        await queryRunner.query(`CREATE TABLE "temporary_item" ("generatedID" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "itemCategoryID" integer NOT NULL, "itemSubcategoryID" integer NOT NULL, "itemSecondarySubCategoryID" integer, "itemID" integer NOT NULL, "name" varchar NOT NULL, "shortDescription" varchar NOT NULL, "longDescription" varchar NOT NULL, "price" integer NOT NULL, "inStock" boolean NOT NULL, "itemTypeTypeID" integer, "itemCategoryCatID" integer, "itemSubCategorySubCatID" integer, "itemSecondarySubCategorySubCatID" integer, CONSTRAINT "FK_afffb0a7530540913cc8651f81f" FOREIGN KEY ("itemSecondarySubCategorySubCatID") REFERENCES "item_sub_category" ("subCatID") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0400fef2a2f4557489b13940fdc" FOREIGN KEY ("itemSubCategorySubCatID") REFERENCES "item_sub_category" ("subCatID") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_b352f619a37b102f8fb8a58fcf7" FOREIGN KEY ("itemCategoryCatID") REFERENCES "item_category" ("catID") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4eae565e0e6ff2ea65ae3aa7ef4" FOREIGN KEY ("itemTypeTypeID") REFERENCES "item_type" ("typeID") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_item"("generatedID", "itemCategoryID", "itemSubcategoryID", "itemSecondarySubCategoryID", "itemID", "name", "shortDescription", "longDescription", "price", "inStock", "itemTypeTypeID", "itemCategoryCatID", "itemSubCategorySubCatID", "itemSecondarySubCategorySubCatID") SELECT "generatedID", "itemCategoryID", "itemSubcategoryID", "itemSecondarySubCategoryID", "itemID", "name", "shortDescription", "longDescription", "price", "inStock", "itemTypeTypeID", "itemCategoryCatID", "itemSubCategorySubCatID", "itemSecondarySubCategorySubCatID" FROM "item"`);
        await queryRunner.query(`DROP TABLE "item"`);
        await queryRunner.query(`ALTER TABLE "temporary_item" RENAME TO "item"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item" RENAME TO "temporary_item"`);
        await queryRunner.query(`CREATE TABLE "item" ("generatedID" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "itemCategoryID" integer NOT NULL, "itemSubcategoryID" integer NOT NULL, "itemSecondarySubCategoryID" integer NOT NULL, "itemID" integer NOT NULL, "name" varchar NOT NULL, "shortDescription" varchar NOT NULL, "longDescription" varchar NOT NULL, "price" integer NOT NULL, "inStock" boolean NOT NULL, "itemTypeTypeID" integer, "itemCategoryCatID" integer, "itemSubCategorySubCatID" integer, "itemSecondarySubCategorySubCatID" integer, CONSTRAINT "FK_afffb0a7530540913cc8651f81f" FOREIGN KEY ("itemSecondarySubCategorySubCatID") REFERENCES "item_sub_category" ("subCatID") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0400fef2a2f4557489b13940fdc" FOREIGN KEY ("itemSubCategorySubCatID") REFERENCES "item_sub_category" ("subCatID") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_b352f619a37b102f8fb8a58fcf7" FOREIGN KEY ("itemCategoryCatID") REFERENCES "item_category" ("catID") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4eae565e0e6ff2ea65ae3aa7ef4" FOREIGN KEY ("itemTypeTypeID") REFERENCES "item_type" ("typeID") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "item"("generatedID", "itemCategoryID", "itemSubcategoryID", "itemSecondarySubCategoryID", "itemID", "name", "shortDescription", "longDescription", "price", "inStock", "itemTypeTypeID", "itemCategoryCatID", "itemSubCategorySubCatID", "itemSecondarySubCategorySubCatID") SELECT "generatedID", "itemCategoryID", "itemSubcategoryID", "itemSecondarySubCategoryID", "itemID", "name", "shortDescription", "longDescription", "price", "inStock", "itemTypeTypeID", "itemCategoryCatID", "itemSubCategorySubCatID", "itemSecondarySubCategorySubCatID" FROM "temporary_item"`);
        await queryRunner.query(`DROP TABLE "temporary_item"`);
        await queryRunner.query(`ALTER TABLE "item" RENAME TO "temporary_item"`);
        await queryRunner.query(`CREATE TABLE "item" ("generatedID" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "itemCategoryID" integer NOT NULL, "itemSubcategoryID" integer NOT NULL, "itemSecondarySubCategoryID" integer NOT NULL, "itemID" integer NOT NULL, "name" varchar NOT NULL, "shortDescription" varchar NOT NULL, "longDescription" varchar NOT NULL, "price" integer NOT NULL, "inStock" boolean NOT NULL, "itemTypeTypeID" integer, "itemCategoryCatID" integer, "itemSubCategorySubCatID" integer, "itemSecondarySubCategorySubCatID" integer, CONSTRAINT "FK_afffb0a7530540913cc8651f81f" FOREIGN KEY ("itemSecondarySubCategorySubCatID") REFERENCES "item_sub_category" ("subCatID") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0400fef2a2f4557489b13940fdc" FOREIGN KEY ("itemSubCategorySubCatID") REFERENCES "item_sub_category" ("subCatID") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_b352f619a37b102f8fb8a58fcf7" FOREIGN KEY ("itemCategoryCatID") REFERENCES "item_category" ("catID") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_4eae565e0e6ff2ea65ae3aa7ef4" FOREIGN KEY ("itemTypeTypeID") REFERENCES "item_type" ("typeID") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "item"("generatedID", "itemCategoryID", "itemSubcategoryID", "itemSecondarySubCategoryID", "itemID", "name", "shortDescription", "longDescription", "price", "inStock", "itemTypeTypeID", "itemCategoryCatID", "itemSubCategorySubCatID", "itemSecondarySubCategorySubCatID") SELECT "generatedID", "itemCategoryID", "itemSubcategoryID", "itemSecondarySubCategoryID", "itemID", "name", "shortDescription", "longDescription", "price", "inStock", "itemTypeTypeID", "itemCategoryCatID", "itemSubCategorySubCatID", "itemSecondarySubCategorySubCatID" FROM "temporary_item"`);
        await queryRunner.query(`DROP TABLE "temporary_item"`);
    }

}
